### PR TITLE
Mongo DB 3.4.4

### PR DESCRIPTION
**Pull request by CyberiumShadow**

### CODE REVIEW

**Comment by CyberiumShadow** [comment]
@icflorescu idk if ur still around

**Comment by icflorescu** [comment]
Yes, I'm still around :-)

Thanks!

**Comment by CyberiumShadow** [comment]
Ah, you might need to bump the cartridge version up as well @icflorescu I forgot to do that in my PR

**Comment by icflorescu** [comment]
I just did, thanks again!

**Pull request merged**
